network:
	ethernets:
    	default:
        	dhcp4: true
        	match:
            	macaddress: 52:54:00:7e:d4:37
    	extra0:
        	dhcp4: true
        	dhcp4-overrides:
            	route-metric: 200
        	match:
            	macaddress: 52:54:00:73:91:45
        	optional: true
    	extra1:
        	dhcp4: false
        	addresses: [192.168.1.40]
        	routes:
           	to: default
           	via: 192.168.1.1
        	match:
           	macaddress: 68:1d:ac:b8:13:ed
        	optional: true
	version: 2

network:
  version: 2
  renderer: networkd
  ethernets:
    default:
      dhcp4: false
      dhcp6: true
      addresses:
        - 10.0.1.11/24
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]  
      routes:
        - to: default
          via: 192.168.1.1
