# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "bento/ubuntu-22.04"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # setup devops user
  config.vm.provision "file", source: "remove_devops.sh", destination: "remove_devops.sh"
  config.vm.provision "file", source: "reset_environment.sh", destination: "reset_environment.sh"
  config.vm.provision "file", source: "setup_initial_user.sh", destination: "setup_initial_user.sh"
  config.vm.provision :shell, :inline => "sudo sh setup_initial_user.sh"

  # config.vm.provision "shell", inline: "sudo apt-get update; sudo ln -sf /usr/bin/python3 /usr/bin/python"
  # config.vm.provision "ansible" do |ans|    
  #   ans.playbook = "setup_initial_user.yaml"
  #   ans.inventory_path = "hosts.ini"
  # end

  # network setup
  config.vm.network "public_network", bridge: "wlp2s0: Wi-Fi (AirPort)", auto_config: true

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.linked_clone = true
  end

  # vagrant server 11.
  config.vm.define "server-101-172" do |app|
    app.vm.hostname = "orc-server-101-172.test"
    app.vm.network :public_network, ip: "192.168.1.173"
  end

  # # vagrant server 12
  # config.vm.define "server-143-242" do |app|
  #   app.vm.hostname = "orc-server-143-242.test"
  #   app.vm.network :public_network, ip: "192.168.1.242"
  # end

  # # vagrant server 13
  # config.vm.define "server-143-243" do |app|
  #   app.vm.hostname = "orc-server-143-243.test"
  #   app.vm.network :public_network, ip: "192.168.1.243"
  # end

  # # vagrant server 13
  # config.vm.define "server-143-244" do |app|
  #   app.vm.hostname = "orc-server-143-244.test"
  #   app.vm.network :public_network, ip: "192.168.1.244"
  # end

  # # vagrant server 13
  # config.vm.define "server-143-245" do |app|
  #   app.vm.hostname = "orc-server-143-245.test"
  #   app.vm.network :public_network, ip: "192.168.1.245"
  # end

end
