# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "bento/ubuntu-22.04"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # port forwarding:
  # config.vm.network "forwarded_port", guest: 80, host: 8080:
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.linked_clone = true
  end

  # vagrant server 01.
  config.vm.define "app" do |app|
    app.vm.hostname = "orc-app1.test"
    app.vm.network :private_network, ip: "192.168.60.201", "forwarded_port", guest: 22, host: 9122:
  end

  # vagrant server 02
  config.vm.define "app" do |app|
    app.vm.hostname = "orc-app2.test"
    app.vm.network :private_network, ip: "192.168.60.202"
  end

  # vagrant server 02
  config.vm.define "app" do |app|
    app.vm.hostname = "orc-app3.test"
    app.vm.network :private_network, ip: "192.168.60.203"
  end

  # # Database server1
  # config.vm.define "db" do |db|
  #   db.vm.hostname = "orc-db1.test"
  #   db.vm.network :private_network, ip: "192.168.60.6"
  # end

  # # Database server2
  # config.vm.define "db" do |db|
  #   db.vm.hostname = "orc-db2.test"
  #   db.vm.network :private_network, ip: "192.168.60.7"
  # end
  # # Database server3
  # config.vm.define "db" do |db|
  #   db.vm.hostname = "orc-db3.test"
  #   db.vm.network :private_network, ip: "192.168.60.8"
  # end
end
