---
# ansible-galaxy install -p ./roles robertdebock.virtualbox
# ansible-galaxy install -p ./roles darkwizard242.vagrant
# ansible-playbook -i hosts.ini install-vagrant.yaml -kK -vvv
- hosts: vagranthosts
  remote_user: devops
  become: yes

  roles: 
  - robertdebock.virtualbox
  - darkwizard242.vagrant

  tasks:
  - name: Show host's ip
    debug:
      msg: "{{ ansible_ssh_host }}"


  - name: Remove vagrant file
    file:
      path: /home/devops/vagrant-deploy/Vagrantfile
      state: absent

  - name: deploy vagrant config
    copy:
      src: sub-hosts/{{ ansible_ssh_host }}/Vagrantfile
      dest: /home/devops/vagrant-deploy/Vagrantfile
      owner: devops
      group: devops
      mode: '0755'
  
  # ISSUE: The IP address configured for the host-only network is not within the allowed range
  # SOLUTION: https://stackoverflow.com/questions/70704093/the-ip-address-configured-for-the-host-only-network-is-not-within-the-allowed-ra
  - name: Remove vagrant file
    file:
      path: sub-hosts/networks.conf
      state: absent

  - name: configure vagrant networks to comply with 192.168.1.0
    copy:
      src: sub-hosts/networks.conf
      dest: /etc/vbox/networks.conf
      owner: root
      group: root
      mode: '0644'
  
  - name: install prerequisites
    apt:
      name: libfuse2
      state: present

  - name: move to vagrant-deploy and launch vms for this host
    shell:
      cmd: vagrant up
      chdir: /home/devops/vagrant-deploy/
    become_user: devops

