---
# ansible-galaxy install -p ./roles robertdebock.virtualbox
# ansible-galaxy install -p ./roles darkwizard242.vagrant
# ansible-playbook -i hosts.ini install-vagrant.yaml -kK -vvv
- hosts: multipass
  remote_user: devops
  become: yes
  
  roles: 
  - robertdebock.virtualbox
  - darkwizard242.vagrant

  tasks:
  - name: Show host's ip
    debug:
      msg: "{{ ansible_ssh_host }}"

