---
# working
# - hosts: app
- hosts: app2
  # connection: local 

  become: true

  tasks:
    - name: Create devops03 user
      user:
        name: devops03
        group: sudo
        password: "{{ 'password' | password_hash('sha512') }}"
        shell: /bin/zsh
        update_password: on_create
      register: devops03
    - name: Force devops03 to change password
      shell: chage -d 0 devops03
      when: devops03.changed
