---
# - hosts: vagranthost107-02
#   remote_user: devops
#   become: yes

#   vars_files:
#     - ../shared_vars/mysql_cluster_vars.yaml

#   roles:
#     - role: ansible-role-mysql

- hosts: vagranthost107-02
  remote_user: devops
  become: yes

  tasks:
  - name: download mysql-shell deb pkg
    ansible.builtin.get_url:
    # url: https://cdn.mysql.com//Downloads/MySQL-Shell/mysql-shell_{{v_major}}.{{v_minor}}.{{v_release}}-.{{v_platform}}.deb
    url: "{{ local_repository }}/mysql-shell/mysql-shell_{{v_major}}.{{v_minor}}.{{v_release}}-{{v_platform}}.deb"
    dest: /home/devops/mysql-shell_{{v_major}}.{{v_minor}}.{{v_release}}-{{v_platform}}.deb
    force: yes

  - name: Install a .deb package
    ansible.builtin.apt:
    deb: /home/devops/mysql-shell_{{v_major}}.{{v_minor}}.{{v_release}}-{{v_platform}}.deb
