---
# ----------------------------------------------------------
# SECTION ONE: install mysql
- hosts: vagranthost107-02
  remote_user: devops
  become: yes

  vars_files:
    - ../shared_vars/mysql_cluster_vars.yaml
  # vars:
  #   # mysql versioning system: https://dev.mysql.com/doc/refman/{{v_major}}.{{v_minor}}/en/which-version.html
  #   v_major: "8"
  #   v_minor: "0"
  #   v_release: "31"
  #   v_platform: "1ubuntu22.04_amd64"

  tasks:
    # --------------------
    # - name: download mysql-shell deb pkg
    #   get_url:
    #     # url: https://cdn.mysql.com//Downloads/MySQL-Shell/mysql-shell_{{v_major}}.{{v_minor}}.{{v_release}}-.{{v_platform}}.deb
    #     url: "{{ local_repository }}/mysql-shell/mysql-shell_{{v_major}}.{{v_minor}}.{{v_release}}-{{v_platform}}.deb"
    #     dest: /home/devops/mysql-shell_{{v_major}}.{{v_minor}}.{{v_release}}-{{v_platform}}.deb
    #     force: yes

    # - name: Install a .deb package
    #   ansible.builtin.apt:
    #     deb: /home/devops/mysql-shell_{{v_major}}.{{v_minor}}.{{v_release}}-{{v_platform}}.deb

    
    - ansible.builtin.include_tasks: "../shared_tasks/install_mysql_shell.yaml"
    