# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
 
    # Configs for haproxy 1 (master)
    config.vm.define :lb-01 do |lb-01_config|
        lb-01_config.vm.provider :virtualbox do |vb_config|
            vb_config.name = "HAProxy 1 - lay4-lb-02-web-02"
        end
        lb-01_config.vm.hostname = "lb-01"
        lb-01_config.vm.network "private_network", ip: "192.168.1.100"
        lb-01_config.vm.provision :shell, path: "lb.sh", env: {"PRIORITY" => "101"}
    end
 
    # Configs for haproxy 2 (backup)
    config.vm.define :lb-02 do |lb-02_config|
        lb-02_config.vm.provider :virtualbox do |vb_config|
            vb_config.name = "HAProxy 2 - lay4-lb-02-web-02"
        end
        lb-02_config.vm.hostname = "lb-02"
        lb-02_config.vm.network "private_network", ip: "192.168.1.104"
        lb-02_config.vm.provision :shell, path: "lb.sh", env: {"PRIORITY" => "100"}
    end
 
    # Configs for web server 1
    config.vm.define :web-01 do |web-01_config|
        web-01_config.vm.provider :virtualbox do |vb_config|
            vb_config.name = "Web Server 1 - lay4-lb-02-web-02"
        end
        web-01_config.vm.hostname = "web-01"
        web-01_config.vm.network "private_network", ip: "192.168.1.101"
        web-01_config.vm.provision :shell, path: "webserver.sh"
    end
 
    # Configs for web server 2
    config.vm.define :web-02 do |web-02_config|
        web-02_config.vm.provider :virtualbox do |vb_config|
            vb_config.name = "Web Server 2 - lay4-lb-02-web-02"
        end
        web-02_config.vm.hostname = "web-02"
        web-02_config.vm.network "private_network", ip: "192.168.1.105"
        web-02_config.vm.provision :shell, path: "webserver.sh"
    end
end