---

- hosts: dstores
  become: true
  gather_facts: true

  roles:
    - robertdebock.bootstrap
    - robertdebock.glusterfs

  vars_files:
    - vars.yml

  tasks:
    - name: apply appropriate hostnames based on expected cluster nodes
      lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
      with_items:
        "{{ cluster_hosts }}"
