# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.e
  config.vm.box = "bento/ubuntu-22.04"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  zone="10"
  # setup devops user
  config.vm.provision "file", source: "../shared-files/remove_devops.sh", destination: "remove_devops.sh"
  config.vm.provision "file", source: "../shared-files/reset_environment.sh", destination: "reset_environment.sh"
  config.vm.provision "file", source: "../shared-files/setup_initial_user.sh", destination: "setup_initial_user.sh"
  config.vm.provision "file", source: "../shared-files/init_cluster.js", destination: "init_cluster.js"
  config.vm.provision "file", source: "../shared-files/build_cluster.js", destination: "build_cluster.js"
  config.vm.provision :shell, :inline => "sudo sh setup_initial_user.sh"
#   config.vm.provision "shell", inline: "sudo apt-get update; sudo ln -sf /usr/bin/python3 /usr/bin/python"
#   config.vm.provision "ansible" do |ans| 
#     ans.playbook = "setup_initial_user.yaml"
#     ans.inventory_path = "hosts.ini"
#   end
  # network setup
  config.vm.network "public_network", auto_config: true
  config.vm.network "forwarded_port", guest: 8443, host: 8443, auto_correct: true
  config.vm.synced_folder "shared/", "/shared/dir1", create: true
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.linked_clone = true
  end
  (156..160).each do |i|
    config.vm.define "cd-#{zone}-#{i}" do |app|
      app.vm.hostname = "cd-#{zone}-#{i}"
      app.vm.network :public_network, ip: "192.168.0.#{i}"
    end
  end
  
  # config.vm.define "cd-db-#{zone}-151" do |app|
  #   app.vm.hostname = "cd-#{zone}-151"
  #   app.vm.network :public_network, ip: "192.168.0.151"
  # end
  
end
