---
- hosts: dstores
  become: yes
  # vars:
  #     git_repo_url: https://github.com/georemo/node-test-proj.git
  #     proj_name: node-test-proj
  #     repo_path: /home/vagrant/node-test-proj
  #     repo_branch: main
  tasks: 

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600  

    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: allow

    - name: install GlusterFS server
      apt: name={{ item }} state=present
      with_items:
        - python3-apt
        - glusterfs-server

    - name: Start and enable GlusterFS server (glusterd) to run on system boot;
      command: "systemctl enable --now glusterd"