---
# INSTALL AND CONFIGURE NGINX

- name: Update repositories cache and install "nginx" package
  ansible.builtin.apt:
    name: nginx
    update_cache: yes

- name: Enable nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
  
- name: Remove nginx site config file1
  file:
    path: /etc/nginx/sites-available/nginx_rev_proxy
    state: absent

- name: Remove nginx site config file2
  file:
    path: /etc/nginx/nginx_rev_proxy
    state: absent

- name: configure nginx.cfg file
  copy:
    src: sub-hosts/{{ ansible_ssh_host }}/nginx_rev_proxy
    dest: /etc/nginx/nginx_rev_proxy


# sudo ln -s /etc/nginx/sites-available/your_domain /etc/nginx/sites-enabled/
# - name: Creating a symlink
#   ansible.builtin.file:
#     src: /etc/nginx/sites-available/nginx_rev_proxy
#     dest: /etc/nginx/sites-enabled/
#     state: link

- name: create symlink for nginx_rev_proxy
  shell:
    cmd: ln -s /etc/nginx/nginx_rev_proxy /etc/nginx/

- name: " nginx service restart"
  service:
    name: nginx
    state: restarted

