---
# INSTALL AND CONFIGURE NGINX
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Enable nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
  
- name: Remove nginx site config file
  file:
    path: /etc/nginx/sites-available/nginx_rev_proxy
    state: absent

- name: configure nginx.cfg file
  copy:
    src: sub-hosts/{{ ansible_ssh_host }}/nginx_rev_proxy
    dest: /etc/nginx/sites-available/nginx_rev_proxy


# sudo ln -s /etc/nginx/sites-available/your_domain /etc/nginx/sites-enabled/
- name: Creating a symlink
  ansible.builtin.file:
    src: /etc/nginx/sites-available/nginx_rev_proxy
    dest: /etc/nginx/sites-enabled/
    state: link

- name: " nginx service restart"
  service:
    name: nginx
    state: restarted

