# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "bento/ubuntu-22.04"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # setup devops user
  config.vm.provision "file", source: "remove_devops.sh", destination: "remove_devops.sh"
  config.vm.provision "file", source: "reset_environment.sh", destination: "reset_environment.sh"
  config.vm.provision "file", source: "setup_initial_user.sh", destination: "setup_initial_user.sh"
  config.vm.provision :shell, :inline => "sudo sh setup_initial_user.sh"

  # config.vm.provision "shell", inline: "sudo apt-get update; sudo ln -sf /usr/bin/python3 /usr/bin/python"
  # config.vm.provision "ansible" do |ans|    
  #   ans.playbook = "setup_initial_user.yaml"
  #   ans.inventory_path = "hosts.ini"
  # end

  # network setup
  config.vm.network "public_network", bridge: "wlp2s0: Wi-Fi (AirPort)", auto_config: true

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.linked_clone = true
  end

  # vagrant server 11.
  config.vm.define "server_137_231" do |app|
    app.vm.hostname = "orc-server_137_231.test"
    app.vm.network :public_network, ip: "192.168.1.231"
  end

  # vagrant server 12
  config.vm.define "server_137_232" do |app|
    app.vm.hostname = "orc-server_137_232.test"
    app.vm.network :public_network, ip: "192.168.1.232"
  end

  # vagrant server 13
  config.vm.define "server_137_233" do |app|
    app.vm.hostname = "orc-server_137_233.test"
    app.vm.network :public_network, ip: "192.168.1.233"
  end

  # vagrant server 13
  config.vm.define "server_137_234" do |app|
    app.vm.hostname = "orc-server_137_234.test"
    app.vm.network :public_network, ip: "192.168.1.234"
  end

  # vagrant server 13
  config.vm.define "server_137_235" do |app|
    app.vm.hostname = "orc-server_137_235.test"
    app.vm.network :public_network, ip: "192.168.1.235"
  end

end
