# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "bento/ubuntu-22.04"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # setup devops user
  config.vm.provision "file", source: "remove_devops.sh", destination: "remove_devops.sh"
  config.vm.provision "file", source: "reset_environment.sh", destination: "reset_environment.sh"
  config.vm.provision "file", source: "setup_initial_user.sh", destination: "setup_initial_user.sh"
  config.vm.provision :shell, :inline => "sudo sh setup_initial_user.sh"

  # config.vm.provision "shell", inline: "sudo apt-get update; sudo ln -sf /usr/bin/python3 /usr/bin/python"
  # config.vm.provision "ansible" do |ans|    
  #   ans.playbook = "setup_initial_user.yaml"
  #   ans.inventory_path = "hosts.ini"
  # end

  # network setup
  config.vm.network "public_network", bridge: "wlp2s0: Wi-Fi (AirPort)", auto_config: true

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.linked_clone = true
  end

  # vagrant server 11.
  config.vm.define "server-186-226" do |app|
    app.vm.hostname = "orc-server-186-226.test"
    app.vm.network :public_network, ip: "192.168.1.226"
  end

  # vagrant server 12
  config.vm.define "server-186-227" do |app|
    app.vm.hostname = "orc-server-186-227.test"
    app.vm.network :public_network, ip: "192.168.1.227"
  end

  # vagrant server 13
  config.vm.define "server-186-228" do |app|
    app.vm.hostname = "orc-app3.test"
    app.vm.network :public_network, ip: "192.168.1.228"
  end

  # vagrant server 12
  config.vm.define "server-186-229" do |app|
    app.vm.hostname = "orc-server-186-229.test"
    app.vm.network :public_network, ip: "192.168.1.229"
  end

  # vagrant server 13
  config.vm.define "server-186-230" do |app|
    app.vm.hostname = "orc-server-186-230.test"
    app.vm.network :public_network, ip: "192.168.1.230"
  end

end
